# Generated by Django 5.1.2 on 2024-10-30 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Serije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Epizoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epizode_date', models.DateField(auto_now_add=True)),
                ('sezona', models.CharField(blank=True, max_length=120, null=True)),
                ('ep', models.CharField(blank=True, max_length=120, null=True)),
                ('epizode_link', models.CharField(max_length=300)),
                ('epizode_preuzmi', models.CharField(default='', max_length=300)),
                ('epizode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.serije')),
            ],
        ),
    ]
