# Generated by Django 5.1.2 on 2024-10-30 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epizoda',
            old_name='epizode_date',
            new_name='ep_date',
        ),
        migrations.RemoveField(
            model_name='epizoda',
            name='ep',
        ),
        migrations.RemoveField(
            model_name='epizoda',
            name='epizode',
        ),
        migrations.RemoveField(
            model_name='epizoda',
            name='sezona',
        ),
        migrations.AddField(
            model_name='epizoda',
            name='title',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='serije',
            name='title',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.CreateModel(
            name='Sezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='home.serije')),
            ],
        ),
        migrations.AddField(
            model_name='epizoda',
            name='season',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='home.sezone'),
        ),
    ]
