# Generated by Django 5.1.2 on 2024-10-30 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_epizode_date_epizoda_ep_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sezone',
            name='tv_show',
        ),
        migrations.DeleteModel(
            name='Epizoda',
        ),
        migrations.DeleteModel(
            name='Serije',
        ),
        migrations.DeleteModel(
            name='Sezone',
        ),
    ]
