# Generated by Django 5.1.2 on 2024-10-30 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_remove_sezone_tv_show_delete_epizoda_delete_serije_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serije',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(default='')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='home.serije')),
            ],
        ),
        migrations.CreateModel(
            name='Epizoda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('ep_date', models.DateField(auto_now_add=True)),
                ('epizode_link', models.CharField(max_length=300)),
                ('epizode_preuzmi', models.CharField(default='', max_length=300)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='home.sezone')),
            ],
        ),
    ]
