# Generated by Django 5.1.2 on 2024-10-31 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_serije_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmovi',
            old_name='published',
            new_name='date',
        ),
    ]
